[project]
name = "dev"
version = "0.0.1"
description = "Tool for managing repository"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "toml",
    "types-toml",
]
