[project]
name = "runo"
version = "0.0.1"
description = "Tool for managing repository"
readme = "README.md"
requires-python = ">=3.8"

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "toml",
]
