name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  static-checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Static type checking
      - name: mypy
        run: ./rego mypy rego tests
      # Linter
      - name: ruff (linter)
        run: ./rego ruff check rego tests
      # Formatter
      - name: ruff (formatter)
        run: ./rego ruff format rego tests --check
#      # Check that version was set correctly
#      - name: version checker
#        run: |
#          expected="rego version: $(git describe --tags)"
#          actual="$(./rego -v)"
#
#          if [ "$actual" = "$expected" ]; then
#            echo "OK"
#          else
#            echo "Version doesn't match expected ($expected)."
#            echo "Make sure you run './rego pre-commit'"
#            exit 1
#          fi

  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # unit tests
      - name: python36
        run: ./rego -c python36 test
      - name: python39
        run: ./rego -c python39 test
      - name: python312
        run: ./rego -c python312 test --cov --cov-report xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  end-to-end-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # e2d tests
      - name: e2e tests
        run: ./rego e2e
