name: dev-it-easy

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  static-checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Static type checking
      - name: mypy
        run: ./dev mypy dev tests
      # Linter
      - name: ruff (linter)
        run: ./dev ruff check dev tests
      # Formatter
      - name: ruff (formatter)
        run: ./dev ruff format dev tests --check
#      # Check that version was set correctly
#      - name: version checker
#        run: |
#          expected="dev version: $(git describe --tags)"
#          actual="$(./dev -v)"
#
#          if [ "$actual" = "$expected" ]; then
#            echo "OK"
#          else
#            echo "Version doesn't match expected ($expected)."
#            echo "Make sure you run './dev pre-commit'"
#            exit 1
#          fi

  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # unit tests
      - name: unit tests
        run: ./dev -c "*" test

  end-to-end-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # e2d tests
      - name: e2e tests
        run: ./dev e2e
