name: rego

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  static-checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Static type checking
      - name: mypy
        run: ./rego mypy rego tests
      # Linter
      - name: ruff (linter)
        run: ./rego ruff check rego tests
      # Formatter
      - name: ruff (formatter)
        run: ./rego ruff format rego tests --check

  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # unit tests
      - name: unit tests
        run: ./rego -c "*" test

  end-to-end-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # e2d tests
      - name: e2e tests
        run: ./rego e2e
